### ISSUE TITLE
Banner: How did you add the text under the banner area? Coz I was duplicating and existing ones still the text not appearing

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Elan-Engineering#21]
![image](https://cloud.githubusercontent.com/assets/13363508/10782481/ac750cdc-7d8b-11e5-9f03-cc4895f7ee2e.png)

**Comment by asif-titan** [comment]
On the page where we can add slides there  is an option to add static slide the text is coming from that slide, which will remain same on all the slides, 
![static-slide](https://cloud.githubusercontent.com/assets/13450796/10875515/4f816080-8159-11e5-8cda-7546599df7fa.png)
![static-slide-2](https://cloud.githubusercontent.com/assets/13450796/10875516/4f83ac96-8159-11e5-8906-e820a74eec0b.png
