### ISSUE TITLE
General - Desktop & Mobile: The loading screen that appears when navigating between pages should be disabled

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Elan-Engineering#26]
![image](https://cloud.githubusercontent.com/assets/13363508/10783296/bf4fb482-7d91-11e5-90ee-aebbe076554b.png)

![image](https://cloud.githubusercontent.com/assets/13363508/10783332/02f85a86-7d92-11e5-94f1-58a92a946f9d.png)

**Comment by asif-titan** [comment]
The page loader has already been disabled, I think that is the slider loading waiting for the images to be loaded

**Comment by maehtitan** [comment]
Why is it that I can't see the loading in this DMS http://alto-capital.stage.titanweb.com.au/?
![image](https://cloud.githubusercontent.com/assets/13363508/11027248/8e5a2dba-86ee-11e5-94c7-65524e42a7b0.png)
