### ISSUE TITLE
Banner Area - Mobile: Banner text is small than the button text

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Elan-Engineering#33]
Devices:
S4 & Itouch ( portrait)
![image](https://cloud.githubusercontent.com/assets/13363508/10783845/95e59252-7d95-11e5-93cf-9d56c6b7c975.png)

Desktop view
![image](https://cloud.githubusercontent.com/assets/13363508/10783859/ab9cbec2-7d95-11e5-8bd5-838ea2be8ef8.png)

**Comment by asif-titan** [comment]
Disable the banner text for mobile devices

**Comment by maehtitan** [comment]
Banner text shouldn't be hidden since there is a button together with the text, you can either position it below the banner or its up to you which is looks good.
