### ISSUE TITLE
Leadins - Mobile: Last lead-in dimension doesn't match from the rest of the leadins, but it is completely the same in itouch and S4 only in Ipad it goes long

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Elan-Engineering#36]
Device: Ipad (portrait & landscape)

![image](https://cloud.githubusercontent.com/assets/13363508/10784245/095e3908-7d98-11e5-8c26-4b84f559bb5d.png)

**Comment by asif-titan** [comment]
As the last lead-in is different form the rest, it contains title which goes for three lines and description too where as the rest of the lead-ins just have a title and image, if I make it same size as the rest then either we have to decrease the font size which won't be readable or will have to set it a height and hide the overflowing content even then the find out more button will overlap the content.
