### ISSUE TITLE
Admin - Forms Notification: Is it okay to use the admin email as the "Sent to Email"? Upon browsing the Business Details I have found another email sales@elaneng.com.au, please clarify. Thanks

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Elan-Engineering#48]
![image](https://cloud.githubusercontent.com/assets/13363508/10809418/73867ce8-7e31-11e5-8409-0077ba65ee6e.png)

**Comment by asif-titan** [comment]
as per the standards the email given as the admin email in the design brief is to be used, but as there is no admin or enquiries email provided in the design brief i have used the general admin email.  
![formt-to-email](https://cloud.githubusercontent.com/assets/13450796/10977541/aa953026-8417-11e5-982d-a08b594cacb2.png)
