### ISSUE TITLE
Header Section: Missing close and open parenthesis in the area code.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Elan-Engineering#80]
![image](https://cloud.githubusercontent.com/assets/13363508/10814146/d21afa5e-7e5e-11e5-981a-798869f9a9c9.png)

**Comment by asif-titan** [comment]
As per the design there are no parenthesis.

**Comment by maehtitan** [comment]
![image](https://cloud.githubusercontent.com/assets/13363508/10926430/57798108-82d2-11e5-9b53-212576b96501.png)
