### ISSUE TITLE
News Single View: There shouldn't be "Blog Articles" in the breadcrumbs

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Elan-Engineering#82]
![image](https://cloud.githubusercontent.com/assets/13363508/11027520/1e6df10a-86f1-11e5-9362-a6e9925f7666.png)

**Comment by asif-titan** [comment]
Blog articles is the category which the post belongs, is it not correct that the post category is shown in the breadcrumb

**Comment by maehtitan** [comment]
Blog Articles is not existing in the design, better change the category to News, and by the way, why is it that the category is displaying in the breadcrumbs based from the other DMS site http://alto-capital.stage.titanweb.com.au/end-of-financial-year-statements/ I am checking only the News and Single News display in the breadcrumbs and no Category found.
