### ISSUE TITLE
Contact Us - Email Field: Accepts invalid email 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Elan-Engineering#83]
![image](https://cloud.githubusercontent.com/assets/13363508/11027657/72a896ca-86f2-11e5-9e1a-f2ea38707847.png)

**Comment by asif-titan** [comment]
As per previous issues raised by the QA team the phone and email field should be required but not validated.

**Comment by maehtitan** [comment]
@asif-titan as per DMS checklist below, Email isn't included to be just a required field only and not validating the email
![image](https://cloud.githubusercontent.com/assets/13363508/11175839/b19a1ae6-8c71-11e5-9d8d-b5037f55db47.png)
