### ISSUE TITLE
W3C - Gallery: 8 Errors

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Elan-Engineering#9]
https://validator.w3.org/nu/?doc=http%3A%2F%2Felaneng.stage.titanweb.com.au%2Fgallery%2F

**Comment by asif-titan** [comment]
Have fixed the errors that could have been fixed the errors regarding the style tag cannot be fixed,
The p element errors are there because of adding the gallery within the visual composer wysiwyg editor which is wrapping the gallery items in a p tag
